apiVersion: v1
kind: Service
metadata:
  name: school-service
spec:
  selector:
    app: school-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.schoolService.containerPort }}
